FROM python:3

# requirements lists dependencies that pip should install (like package.json for node.js)
COPY requirements.txt /requirements.txt

RUN pip install -r requirements.txt

COPY deploy.py /deploy.py

CMD ["python", "/deploy.py"]